version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: zenohub
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  python-server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASSWORD: mypassword