[tool.poetry]
name = "connex"
version = "0.1.0"
description = ""
authors = ["Alex Bäuerle <alex@a13x.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
