name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: cd frontend && npm i
      - name: linting
        run: cd frontend && npm run lint

  check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: cd frontend && npm i
      - name: Svelte check
        run: cd frontend && npm run check

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "backend/zeno_backend/"
      - uses: chartboost/ruff-action@v1
        with:
          args: "format --check"
          src: "backend/zeno_backend/"

  typecheck-python:
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v1

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Set up secrets
        run: echo "${{ secrets.ZENO_HUB_ENV }}" > frontend/.env
      - name: Install node
        run: |
          cd frontend
          npm ci
      - name: Set up docker containers
        run: |
          docker-compose -f ./docker-compose-test.yml up -d
      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
